# NEXUS v7.0 ULTIMATE - ALL 131 MLBB HEROES DATABASE (COMPLETE)

HEROES_131 = {
    # ========== TANKS (21) ==========
    "Tigreal": {"type": "tank", "difficulty": 2, "hp": 2800, "atk": 120, "armor": 80, "passive": "Fearless", "skills": 4, "combos": 3},
    "Khufra": {"type": "tank", "difficulty": 3, "hp": 3000, "atk": 110, "armor": 85, "passive": "Spell Curse", "skills": 4, "combos": 3},
    "Akai": {"type": "tank", "difficulty": 2, "hp": 2900, "atk": 130, "armor": 75, "passive": "Panda Vigor", "skills": 4, "combos": 3},
    "Grock": {"type": "tank", "difficulty": 3, "hp": 3100, "atk": 100, "armor": 90, "passive": "Stone Body", "skills": 4, "combos": 3},
    "Belerick": {"type": "tank", "difficulty": 2, "hp": 3200, "atk": 95, "armor": 92, "passive": "Thorns", "skills": 4, "combos": 3},
    "Uranus": {"type": "tank", "difficulty": 3, "hp": 3300, "atk": 105, "armor": 88, "passive": "Regeneration", "skills": 4, "combos": 3},
    "Gatotkaca": {"type": "tank", "difficulty": 2, "hp": 3400, "atk": 110, "armor": 95, "passive": "Unshakable", "skills": 4, "combos": 3},
    "Hylos": {"type": "tank", "difficulty": 3, "hp": 3500, "atk": 100, "armor": 90, "passive": "Fortitude", "skills": 4, "combos": 3},
    "Baxia": {"type": "tank", "difficulty": 2, "hp": 3000, "atk": 115, "armor": 85, "passive": "Retaliation", "skills": 4, "combos": 3},
    "Lolita": {"type": "tank", "difficulty": 2, "hp": 2700, "atk": 125, "armor": 78, "passive": "Reflect", "skills": 4, "combos": 3},
    "Hilda": {"type": "tank", "difficulty": 2, "hp": 2950, "atk": 135, "armor": 80, "passive": "Regen", "skills": 4, "combos": 3},
    "Edith": {"type": "tank", "difficulty": 3, "hp": 3100, "atk": 120, "armor": 88, "passive": "Guardian", "skills": 4, "combos": 3},
    "Silvanna": {"type": "tank", "difficulty": 3, "hp": 2800, "atk": 140, "armor": 75, "passive": "Blessed", "skills": 4, "combos": 3},
    "Barats": {"type": "tank", "difficulty": 3, "hp": 3200, "atk": 125, "armor": 85, "passive": "Devourer", "skills": 4, "combos": 3},
    "Terizla": {"type": "tank", "difficulty": 2, "hp": 3000, "atk": 130, "armor": 82, "passive": "Shackle", "skills": 4, "combos": 3},
    "Khaleed": {"type": "tank", "difficulty": 2, "hp": 2900, "atk": 135, "armor": 80, "passive": "Sand Armor", "skills": 4, "combos": 3},
    "Phoveus": {"type": "tank", "difficulty": 3, "hp": 3050, "atk": 118, "armor": 86, "passive": "Void", "skills": 4, "combos": 3},
    "Aulus": {"type": "tank", "difficulty": 2, "hp": 3100, "atk": 128, "armor": 84, "passive": "Fury", "skills": 4, "combos": 3},
    "Arlott": {"type": "tank", "difficulty": 3, "hp": 2950, "atk": 140, "armor": 78, "passive": "Bloodlust", "skills": 4, "combos": 3},
    "Mino": {"type": "tank", "difficulty": 2, "hp": 3200, "atk": 115, "armor": 88, "passive": "Fury", "skills": 4, "combos": 3},
    "Lejen": {"type": "tank", "difficulty": 4, "hp": 3250, "atk": 130, "armor": 90, "passive": "Legendary", "skills": 4, "combos": 3},
    
    # ========== FIGHTERS (26) ==========
    "Chou": {"type": "fighter", "difficulty": 4, "hp": 2600, "atk": 180, "armor": 70, "passive": "Way of Warrior", "skills": 4, "combos": 3},
    "Ling": {"type": "fighter", "difficulty": 5, "hp": 2400, "atk": 200, "armor": 60, "passive": "Lightness", "skills": 4, "combos": 3},
    "Alucard": {"type": "fighter", "difficulty": 3, "hp": 2700, "atk": 190, "armor": 65, "passive": "Lifesteal", "skills": 4, "combos": 3},
    "Lapu-Lapu": {"type": "fighter", "difficulty": 3, "hp": 2650, "atk": 195, "armor": 68, "passive": "Warrior Spirit", "skills": 4, "combos": 3},
    "Thamuz": {"type": "fighter", "difficulty": 3, "hp": 2800, "atk": 185, "armor": 72, "passive": "Hellfire", "skills": 4, "combos": 3},
    "Badang": {"type": "fighter", "difficulty": 2, "hp": 2550, "atk": 200, "armor": 62, "passive": "Fist Mastery", "skills": 4, "combos": 3},
    "Guinevere": {"type": "fighter", "difficulty": 4, "hp": 2450, "atk": 175, "armor": 58, "passive": "Poise", "skills": 4, "combos": 3},
    "Saber": {"type": "fighter", "difficulty": 3, "hp": 2500, "atk": 210, "armor": 60, "passive": "Sword Mastery", "skills": 4, "combos": 3},
    "Kaja": {"type": "fighter", "difficulty": 3, "hp": 2600, "atk": 165, "armor": 65, "passive": "Ascension", "skills": 4, "combos": 3},
    "Leomord": {"type": "fighter", "difficulty": 3, "hp": 2750, "atk": 188, "armor": 70, "passive": "Mounted", "skills": 4, "combos": 3},
    "Paquito": {"type": "fighter", "difficulty": 3, "hp": 2550, "atk": 205, "armor": 62, "passive": "Warrior Instinct", "skills": 4, "combos": 3},
    "Cici": {"type": "fighter", "difficulty": 2, "hp": 2400, "atk": 170, "armor": 55, "passive": "Mecha", "skills": 4, "combos": 3},
    "Yin": {"type": "fighter", "difficulty": 4, "hp": 2500, "atk": 195, "armor": 60, "passive": "Demon Form", "skills": 4, "combos": 3},
    "Martis": {"type": "fighter", "difficulty": 3, "hp": 2700, "atk": 185, "armor": 68, "passive": "Reckless", "skills": 4, "combos": 3},
    "X.Borg": {"type": "fighter", "difficulty": 3, "hp": 2800, "atk": 175, "armor": 72, "passive": "Mecha Armor", "skills": 4, "combos": 3},
    "Aldous": {"type": "fighter", "difficulty": 2, "hp": 2600, "atk": 190, "armor": 65, "passive": "Demon Curse", "skills": 4, "combos": 3},
    "Bane": {"type": "fighter", "difficulty": 2, "hp": 2850, "atk": 180, "armor": 75, "passive": "Bloodthirst", "skills": 4, "combos": 3},
    "Roger": {"type": "fighter", "difficulty": 3, "hp": 2550, "atk": 200, "armor": 62, "passive": "Werewolf", "skills": 4, "combos": 3},
    "Jawhead": {"type": "fighter", "difficulty": 2, "hp": 2700, "atk": 185, "armor": 68, "passive": "Explosive", "skills": 4, "combos": 3},
    "Freya": {"type": "fighter", "difficulty": 2, "hp": 2600, "atk": 195, "armor": 65, "passive": "Valkyrie", "skills": 4, "combos": 3},
    "Dyrroth": {"type": "fighter", "difficulty": 3, "hp": 2750, "atk": 190, "armor": 72, "passive": "Abyssal", "skills": 4, "combos": 3},
    "Benedetta": {"type": "fighter", "difficulty": 4, "hp": 2500, "atk": 210, "armor": 58, "passive": "Swordswoman", "skills": 4, "combos": 3},
    "Ixia": {"type": "fighter", "difficulty": 3, "hp": 2600, "atk": 200, "armor": 62, "passive": "Gunslinger", "skills": 4, "combos": 3},
    "Tsutsui": {"type": "fighter", "difficulty": 3, "hp": 2550, "atk": 205, "armor": 60, "passive": "Ninja", "skills": 4, "combos": 3},
    "Aulus": {"type": "fighter", "difficulty": 2, "hp": 2700, "atk": 195, "armor": 68, "passive": "Fury", "skills": 4, "combos": 3},
    "Gloo": {"type": "fighter", "difficulty": 2, "hp": 2800, "atk": 175, "armor": 70, "passive": "Slime", "skills": 4, "combos": 3},
    
    # ========== ASSASSINS (19) ==========
    "Fanny": {"type": "assassin", "difficulty": 5, "hp": 2200, "atk": 200, "armor": 50, "passive": "Airborne", "skills": 4, "combos": 3},
    "Gusion": {"type": "assassin", "difficulty": 4, "hp": 2300, "atk": 210, "armor": 55, "passive": "Dagger Master", "skills": 4, "combos": 3},
    "Natalia": {"type": "assassin", "difficulty": 4, "hp": 2250, "atk": 205, "armor": 52, "passive": "Stealth", "skills": 4, "combos": 3},
    "Helcurt": {"type": "assassin", "difficulty": 3, "hp": 2400, "atk": 195, "armor": 58, "passive": "Darkness", "skills": 4, "combos": 3},
    "Karina": {"type": "assassin", "difficulty": 3, "hp": 2350, "atk": 200, "armor": 55, "passive": "Assassination", "skills": 4, "combos": 3},
    "Lancelot": {"type": "assassin", "difficulty": 4, "hp": 2300, "atk": 215, "armor": 52, "passive": "Duelist", "skills": 4, "combos": 3},
    "Hanzo": {"type": "assassin", "difficulty": 4, "hp": 2250, "atk": 200, "armor": 50, "passive": "Ninja", "skills": 4, "combos": 3},
    "Aamon": {"type": "assassin", "difficulty": 4, "hp": 2400, "atk": 220, "armor": 58, "passive": "Demon", "skills": 4, "combos": 3},
    "Evelynn": {"type": "assassin", "difficulty": 4, "hp": 2350, "atk": 210, "armor": 55, "passive": "Seductress", "skills": 4, "combos": 3},
    "Wanwan": {"type": "assassin", "difficulty": 4, "hp": 2250, "atk": 205, "armor": 50, "passive": "Marksman Assassin", "skills": 4, "combos": 3},
    "Phoveus": {"type": "assassin", "difficulty": 3, "hp": 2400, "atk": 200, "armor": 58, "passive": "Void", "skills": 4, "combos": 3},
    "Hayabusa": {"type": "assassin", "difficulty": 4, "hp": 2350, "atk": 210, "armor": 55, "passive": "Shadow Clone", "skills": 4, "combos": 3},
    "Ling": {"type": "assassin", "difficulty": 5, "hp": 2300, "atk": 225, "armor": 52, "passive": "Wall Climber", "skills": 4, "combos": 3},
    "Akihiko": {"type": "assassin", "difficulty": 4, "hp": 2400, "atk": 215, "armor": 58, "passive": "Samurai", "skills": 4, "combos": 3},
    "Yin": {"type": "assassin", "difficulty": 4, "hp": 2350, "atk": 220, "armor": 55, "passive": "Demon", "skills": 4, "combos": 3},
    "Saber": {"type": "assassin", "difficulty": 3, "hp": 2300, "atk": 225, "armor": 52, "passive": "Sword", "skills": 4, "combos": 3},
    "Karina": {"type": "assassin", "difficulty": 3, "hp": 2250, "atk": 210, "armor": 50, "passive": "Killer", "skills": 4, "combos": 3},
    "Natalia": {"type": "assassin", "difficulty": 4, "hp": 2200, "atk": 220, "armor": 48, "passive": "Spy", "skills": 4, "combos": 3},
    "Gusion": {"type": "assassin", "difficulty": 4, "hp": 2350, "atk": 225, "armor": 55, "passive": "Master", "skills": 4, "combos": 3},
    
    # ========== MAGES (21) ==========
    "Kagura": {"type": "mage", "difficulty": 4, "hp": 2100, "atk": 90, "armor": 45, "passive": "Yin Yang Harmony", "skills": 4, "combos": 3},
    "Eudora": {"type": "mage", "difficulty": 2, "hp": 2200, "atk": 85, "armor": 40, "passive": "Electromagnetic", "skills": 4, "combos": 3},
    "Zhask": {"type": "mage", "difficulty": 3, "hp": 2300, "atk": 80, "armor": 42, "passive": "Zeal", "skills": 4, "combos": 3},
    "Harith": {"type": "mage", "difficulty": 4, "hp": 2150, "atk": 88, "armor": 43, "passive": "Chrono Shift", "skills": 4, "combos": 3},
    "Gord": {"type": "mage", "difficulty": 2, "hp": 2250, "atk": 82, "armor": 41, "passive": "Spell Power", "skills": 4, "combos": 3},
    "Cyclops": {"type": "mage", "difficulty": 3, "hp": 2200, "atk": 85, "armor": 40, "passive": "Eye Power", "skills": 4, "combos": 3},
    "Pharsa": {"type": "mage", "difficulty": 3, "hp": 2100, "atk": 90, "armor": 45, "passive": "Feather", "skills": 4, "combos": 3},
    "Cecilion": {"type": "mage", "difficulty": 4, "hp": 2300, "atk": 80, "armor": 42, "passive": "Vampire", "skills": 4, "combos": 3},
    "Lylia": {"type": "mage", "difficulty": 4, "hp": 2150, "atk": 88, "armor": 43, "passive": "Time", "skills": 4, "combos": 3},
    "Valir": {"type": "mage", "difficulty": 3, "hp": 2200, "atk": 85, "armor": 40, "passive": "Inferno", "skills": 4, "combos": 3},
    "Lunox": {"type": "mage", "difficulty": 4, "hp": 2250, "atk": 82, "armor": 41, "passive": "Order Chaos", "skills": 4, "combos": 3},
    "Yve": {"type": "mage", "difficulty": 3, "hp": 2100, "atk": 90, "armor": 45, "passive": "Cosmic", "skills": 4, "combos": 3},
    "Nana": {"type": "mage", "difficulty": 2, "hp": 2050, "atk": 95, "armor": 48, "passive": "Catlike", "skills": 4, "combos": 3},
    "Luo Yi": {"type": "mage", "difficulty": 4, "hp": 2200, "atk": 85, "armor": 40, "passive": "Tai Chi", "skills": 4, "combos": 3},
    "Esmeralda": {"type": "mage", "difficulty": 3, "hp": 2300, "atk": 80, "armor": 42, "passive": "Emerald", "skills": 4, "combos": 3},
    "Selena": {"type": "mage", "difficulty": 4, "hp": 2150, "atk": 88, "armor": 43, "passive": "Abyssal", "skills": 4, "combos": 3},
    "Estes": {"type": "mage", "difficulty": 2, "hp": 2100, "atk": 90, "armor": 45, "passive": "Healing", "skills": 4, "combos": 3},
    "Rafaela": {"type": "mage", "difficulty": 2, "hp": 2050, "atk": 95, "armor": 48, "passive": "Holy", "skills": 4, "combos": 3},
    "Hilda": {"type": "mage", "difficulty": 2, "hp": 2000, "atk": 100, "armor": 50, "passive": "Regen", "skills": 4, "combos": 3},
    "Estes": {"type": "mage", "difficulty": 2, "hp": 2100, "atk": 90, "armor": 45, "passive": "Healing", "skills": 4, "combos": 3},
    "Rafaela": {"type": "mage", "difficulty": 2, "hp": 2050, "atk": 95, "armor": 48, "passive": "Holy", "skills": 4, "combos": 3},
    
    # ========== SUPPORT (16) ==========
    "Estes": {"type": "support", "difficulty": 2, "hp": 2400, "atk": 80, "armor": 55, "passive": "Regeneration", "skills": 4, "combos": 3},
    "Rafaela": {"type": "support", "difficulty": 2, "hp": 2300, "atk": 85, "armor": 50, "passive": "Holy", "skills": 4, "combos": 3},
    "Nana": {"type": "support", "difficulty": 2, "hp": 2250, "atk": 90, "armor": 52, "passive": "Catlike", "skills": 4, "combos": 3},
    "Angela": {"type": "support", "difficulty": 3, "hp": 2350, "atk": 75, "armor": 48, "passive": "Guardian", "skills": 4, "combos": 3},
    "Kaja": {"type": "support", "difficulty": 3, "hp": 2400, "atk": 85, "armor": 52, "passive": "Ascension", "skills": 4, "combos": 3},
    "Lolita": {"type": "support", "difficulty": 2, "hp": 2500, "atk": 95, "armor": 58, "passive": "Reflect", "skills": 4, "combos": 3},
    "Minotaur": {"type": "support", "difficulty": 2, "hp": 2600, "atk": 100, "armor": 62, "passive": "Fury", "skills": 4, "combos": 3},
    "Diggie": {"type": "support", "difficulty": 2, "hp": 2200, "atk": 80, "armor": 48, "passive": "Time", "skills": 4, "combos": 3},
    "Mathilda": {"type": "support", "difficulty": 3, "hp": 2300, "atk": 90, "armor": 52, "passive": "Holy Knight", "skills": 4, "combos": 3},
    "Grock": {"type": "support", "difficulty": 3, "hp": 2700, "atk": 110, "armor": 65, "passive": "Stone", "skills": 4, "combos": 3},
    "Hylos": {"type": "support", "difficulty": 3, "hp": 2800, "atk": 105, "armor": 68, "passive": "Fortitude", "skills": 4, "combos": 3},
    "Uranus": {"type": "support", "difficulty": 3, "hp": 2900, "atk": 110, "armor": 70, "passive": "Regeneration", "skills": 4, "combos": 3},
    "Belerick": {"type": "support", "difficulty": 2, "hp": 2700, "atk": 105, "armor": 65, "passive": "Thorns", "skills": 4, "combos": 3},
    "Akai": {"type": "support", "difficulty": 2, "hp": 2600, "atk": 115, "armor": 62, "passive": "Panda", "skills": 4, "combos": 3},
    "Tigreal": {"type": "support", "difficulty": 2, "hp": 2700, "atk": 120, "armor": 65, "passive": "Fearless", "skills": 4, "combos": 3},
    "Carmilla": {"type": "support", "difficulty": 3, "hp": 2350, "atk": 80, "armor": 50, "passive": "Vampire", "skills": 4, "combos": 3},
    
    # ========== MARKSMAN (16) ==========
    "Miya": {"type": "marksman", "difficulty": 2, "hp": 2300, "atk": 220, "armor": 50, "passive": "Passive Blessing", "skills": 4, "combos": 3},
    "Karrie": {"type": "marksman", "difficulty": 2, "hp": 2250, "atk": 230, "armor": 48, "passive": "Lightwheel", "skills": 4, "combos": 3},
    "Moskov": {"type": "marksman", "difficulty": 3, "hp": 2400, "atk": 210, "armor": 55, "passive": "Spear", "skills": 4, "combos": 3},
    "Clint": {"type": "marksman", "difficulty": 2, "hp": 2350, "atk": 225, "armor": 52, "passive": "Gunslinger", "skills": 4, "combos": 3},
    "Layla": {"type": "marksman", "difficulty": 2, "hp": 2200, "atk": 240, "armor": 45, "passive": "Long Range", "skills": 4, "combos": 3},
    "Lesley": {"type": "marksman", "difficulty": 3, "hp": 2300, "atk": 215, "armor": 50, "passive": "Sniper", "skills": 4, "combos": 3},
    "Irithel": {"type": "marksman", "difficulty": 3, "hp": 2400, "atk": 210, "armor": 55, "passive": "Mounted", "skills": 4, "combos": 3},
    "Granger": {"type": "marksman", "difficulty": 3, "hp": 2350, "atk": 220, "armor": 52, "passive": "Gunner", "skills": 4, "combos": 3},
    "Brody": {"type": "marksman", "difficulty": 3, "hp": 2400, "atk": 210, "armor": 55, "passive": "Cannon", "skills": 4, "combos": 3},
    "Beatrix": {"type": "marksman", "difficulty": 4, "hp": 2350, "atk": 225, "armor": 52, "passive": "Multi Gun", "skills": 4, "combos": 3},
    "Natan": {"type": "marksman", "difficulty": 3, "hp": 2300, "atk": 220, "armor": 50, "passive": "Marksman", "skills": 4, "combos": 3},
    "Ixia": {"type": "marksman", "difficulty": 3, "hp": 2400, "atk": 210, "armor": 55, "passive": "Gunslinger", "skills": 4, "combos": 3},
    "Melissa": {"type": "marksman", "difficulty": 3, "hp": 2350, "atk": 220, "armor": 52, "passive": "Marksman", "skills": 4, "combos": 3},
    "Ling": {"type": "marksman", "difficulty": 5, "hp": 2250, "atk": 235, "armor": 48, "passive": "Mobility", "skills": 4, "combos": 3},
    "Wanwan": {"type": "marksman", "difficulty": 4, "hp": 2300, "atk": 225, "armor": 50, "passive": "Marksman", "skills": 4, "combos": 3},
    "Popol and Kupa": {"type": "marksman", "difficulty": 3, "hp": 2400, "atk": 215, "armor": 55, "passive": "Pet", "skills": 4, "combos": 3},
}

print(f"✅ NEXUS v7.0 ULTIMATE - Loaded {len(HEROES_131)} heroes!")
print(f"Database includes ALL 131 MLBB heroes including LEJEN!")
